# Generated by Django 6.0.5 on 2026-05-28 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSDTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('group_type', models.CharField(choices=[('MALE', 'Male Clinics'), ('FEMALE', 'Female Clinics'), ('SPECIALTY', 'Specialty Clinics'), ('EMERGENCY', 'Emergency Clinics'), ('CSSD', 'CSSD')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CSSDRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('SENT_TO_CSSD', 'Sent to CSSD'), ('RECEIVED_BY_CSSD', 'Received by CSSD'), ('RETURNED_TO_CLINIC', 'Returned to Clinic'), ('CONFIRMED_BY_CLINIC', 'Confirmed by Clinic'), ('CLOSED', 'Closed')], default='SENT_TO_CSSD', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cssd_requests', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssd.location')),
            ],
        ),
        migrations.CreateModel(
            name='CSSDRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cssd_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_templates', to='cssd.cssdrequest')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cssd.cssdtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CSSDRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=150)),
                ('quantity_sent', models.PositiveIntegerField(default=0)),
                ('quantity_received_by_cssd', models.PositiveIntegerField(default=0)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('cssd_request_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='cssd.cssdrequesttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CSSDTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cssd.cssdtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(choices=[('MALE', 'Male Clinics'), ('FEMALE', 'Female Clinics'), ('SPECIALTY', 'Specialty Clinics'), ('EMERGENCY', 'Emergency Clinics'), ('CSSD', 'CSSD'), ('ADMIN', 'Admin')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cssd_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cssd.cssdrequest')),
            ],
        ),
    ]
