# Generated by Django 6.0.5 on 2026-05-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssdrequestitem',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
