# Generated by Django 6.0.5 on 2026-05-29 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cssd', '0002_cssdrequestitem_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cssdrequestitem',
            name='cssd_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cssd.cssdrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cssdrequestitem',
            name='cssd_request_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='cssd.cssdrequesttemplate'),
        ),
    ]
